### ISSUE TITLE
Blosxom weblog software requires ISP provided server space 

### ISSUE THREAD

**Issue by dennisgit42** [sinker/tacofancy#197]
I am making an open source contribution for first time and installed Markdown. Markdown requires one of two web loggers, I decided to use Blosxom weblogging since the only other option is Movable Type, which requires a paid license. Here are the requirements for installing and using Blosxom: http://blosxom.sourceforge.net/documentation/users/install/dynamic/isp.html
I am pretty sure that I do not have any space allotted to me by my ISP for my own website where I can run CGI scripts, and I run windows 8 on my only machine, so I am sure the other options discussed here: http://blosxom.sourceforge.net/documentation/users/install/dynamic/  do not apply for me. 

With this in mind, how can I contribute to this project without paying for additional software / hosting I don't normally use or need?

**Comment by dennisgit42** [comment]
Sorry if this is dumb question, but would this suit my needs? http://www.host-ed.net/

**Comment by booc0mtaco** [comment]
What exactly are you trying to do? To contribute here, you should only need some git tool (like `git` on the command line), and an editor for text or markdown files.

**Comment by knowtheory** [comment]
lol github spam.

Hey @dennisgit42 what's the cube root of 8?

**Comment by booc0mtaco** [comment]
@knowtheory Good call! There was enough in that account to make me think it was a very confused user.

**Comment by knowtheory** [comment]
I also edited all the links so that nobody accidentally clicks through on them.

And for anyone interested in how weird the spam gets, Dennis Git's github profile is filled with commits that look like they're scraped from places like StackOverflow.

For example this commit: https://github.com/dennisgit42/todo/commit/add232d905e968dc0d4ee07f682c1669c7afa9d7 from 21 days ago appears to be lifted from this StackOverflow post: https://stackoverflow.com/questions/39467749/delete-from-database-with-javascript from last year.

**Comment by knowtheory** [comment]
I might still be jumping the gun, in which case, i will profusely apologize, but if in those circumstances i will also be very confused :)

Also, if that turns out to be the case, i would be very happy to personally help @dennisgit42 get set up to contribute taco recipes!

**Comment by dennisgit42** [comment]
Actually, I am a human user trying to practice contributing to open source. I am trying to write up a recipe for the tacofancy repo using markdown, as described in the docs.  I am unsure of how to do this given the problem I described.

**Comment by dennisgit42** [comment]
Actually, I am a human user trying to practice contributing to open source. I am unsure of how to do this given the problem I described.  Sincerely,  Dennis Ouyangden2net@yahoo.com609-933-6493 

    On Tuesday, July 11, 2017 12:43 AM, Ted Han <notifications@github.com> wrote:
 

 I might still be jumping the gun, in which case, i will profusely apologize, but if in those circumstances i will also be very confused :)Also, if that turns out to be the case, i would be very happy to personally help @dennisgit42 get set up to contribute taco recipes!—

**Comment by dennisgit42** [comment]
Could booc0mtaco explain why only git and text editor are necessary? Based on what I was reading here: https://daringfireball.net/projects/markdown/  I have to first install markdown, then a web writer like Bloxsom, and use Bloxsom with markdown configured.

**Comment by booc0mtaco** [comment]
@dennisgit42 OK, we can step thru this process if you want. Hopefully there was no offense!

---

So, all that you're reading about markdown is a red herring when dealing with github. Gruber's page is for people who plan on using some CMS on their own site to write and post markdown content. On github.com, this is handled for you. This repository only contains text files, and the web pages have code to do formatting (e.g., You don't install anything to get color coding for your code files like JavaScript, and you similarly don't need to install anything to handle markdown files and their formatting).

In fact, these comment fields (yes, the very ones you are using now) support markdown! You can make things **bold**, *italic*, or make them `look like inline code`. You can see all of this by clicking "preview" as you type a comment.

If you're only interested in adding new recipes, find one that you like here, and [view it's raw source](https://raw.githubusercontent.com/sinker/tacofancy/master/full_tacos/asian_style_tacos.md). See there? It's just text. Github.com effectively is your bloxsom/whatever.

For an editor, I'd honestly recommend learning markdown syntax and using a plain text editor. If you want something more visual, You can use a tool like MacDown or [typora](https://typora.io). Once you're creating your own recipes, you can submit "Pull Requests" to have them added to this repository. In the most basic workflow, you can simply use github itself. That way, there's no need for any external tools; just navigate to the directory you want, click "create new file," and follow the on-screen instructions for submitting this new recipe.

--- 

Hope that's enough to get you on the right path!

**Comment by knowtheory** [comment]
@dennisgit42 Oh man, I'm so sorry for assuming!  I'd be happy to help you with github & markdown, my email address is in my profile if you'd like to reach me there, i'm happy to help out on specifics.

As a general matter, Markdown is just a file format.  There are many tools (some are websites, some are tools you can run on your own machine) which will read markdown files and display them as HTML.  Github automatically does this in fact.  Any file that has a .md extension can be viewed as HTML (for example the [index.md](https://github.com/sinker/tacofancy/blob/master/INDEX.md)) as well as edited as markdown & text ([see the editing link that github its pages](https://github.com/sinker/tacofancy/edit/master/INDEX.md)).

If you're running a website which takes user input, there are tools which will take those user contributions and convert them from markdown into HTML snippets automatically (like what Github is doing).  But in the case of Tacofancy, that's not the intent/design of how folks contribute their taco recipes.

So! Happy to walk through any of this with you here, or via email, or the medium of your choice.  Apologies again!

**Comment by dennisgit42** [comment]
No problem, glad we could clear that up. I will try to type up my recipe in the markdown format and submit a pull request.  Sincerely,  Dennis Ouyangden2net@yahoo.com609-933-6493 

    On Tuesday, July 11, 2017 10:04 AM, Ted Han <notifications@github.com> wrote:
 

 @dennisgit42 Oh man, I'm so sorry for assuming! I'd be happy to help you with github & markdown, my email address is in my profile if you'd like to reach me there, i'm happy to help out on specifics.As a general matter, Markdown is just a file format. There are many tools (some are websites, some are tools you can run on your own machine) which will read markdown files and display them as HTML. Github automatically does this in fact. Any file that has a .md extension can be viewed as HTML (for example the index.md) as well as edited as markdown & text (see the editing link that github its pages).If you're running a website which takes user input, there are tools which will take those user contributions and convert them from markdown into HTML snippets automatically (like what Github is doing). But in the case of Tacofancy, that's not the intent/design of how folks contribute their taco recipes.So! Happy to walk through any of this with you here, or via email, or the medium of your choice. Apologies again!—

**Comment by dennisgit42** [comment]
Question, when using markdown, is it possible to add more than one line break between paragraphs? For example: 
This is my first paragraph<empty line><empty line><empty line>This is my second paragraph. 

I tried using multiple returns, as well as lines with nothing on them except for two or more spaces, but each time I only get one blank line. Sincerely,  Dennis Ouyangden2net@yahoo.com609-933-6493 

    On Tuesday, July 11, 2017 4:26 PM, Dennis Ouyang <den2net@yahoo.com> wrote:
 

 No problem, glad we could clear that up. I will try to type up my recipe in the markdown format and submit a pull request.  Sincerely,  Dennis Ouyangden2net@yahoo.com609-933-6493 

    On Tuesday, July 11, 2017 10:04 AM, Ted Han <notifications@github.com> wrote:
 

 @dennisgit42 Oh man, I'm so sorry for assuming! I'd be happy to help you with github & markdown, my email address is in my profile if you'd like to reach me there, i'm happy to help out on specifics.As a general matter, Markdown is just a file format. There are many tools (some are websites, some are tools you can run on your own machine) which will read markdown files and display them as HTML. Github automatically does this in fact. Any file that has a .md extension can be viewed as HTML (for example the index.md) as well as edited as markdown & text (see the editing link that github its pages).If you're running a website which takes user input, there are tools which will take those user contributions and convert them from markdown into HTML snippets automatically (like what Github is doing). But in the case of Tacofancy, that's not the intent/design of how folks contribute their taco recipes.So! Happy to walk through any of this with you here, or via email, or the medium of your choice. Apologies again!—
